### ISSUE TITLE
运行成了，但是问问题报错退出

### ISSUE THREAD

**Issue by lxy4856971** [xtymbbt/pandora-wechat#1]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x66195b]

goroutine 33 [running]:
pandora-wechat/pandoraGpt.Completions({0xc000277000, 0xe}, {0x94c7e8, 0x1}, {0xc0000dfe70?, 0xc00036d000?})
        /root/pandora-wechat-main/pandoraGpt/pandora.go:57 +0x7b
pandora-wechat/handlers.(*UserMessageHandler).ReplyText(0x6c51a0?, 0xc00009a500)
        /root/pandora-wechat-main/handlers/user_msg_handler.go:41 +0x1ba
pandora-wechat/handlers.(*UserMessageHandler).handle(0x6d3ee0?, 0xc00007f0e0?)
        /root/pandora-wechat-main/handlers/user_msg_handler.go:22 +0x2a
pandora-wechat/handlers.Handler(0xc00009a500)
        /root/pandora-wechat-main/handlers/handler.go:41 +0xb8
github.com/eatmoreapple/openwechat.(*Bot).syncCheck(0xc0000d4000)
        /root/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.2/bot.go:257 +0x21a
github.com/eatmoreapple/openwechat.(*Bot).WebInit.func1()
        /root/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.2/bot.go:178 +0x68
created by github.com/eatmoreapple/openwechat.(*Bot).WebInit
        /root/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.2/bot.go:173 +0x28b
exit status 2

**Comment by xtymbbt** [comment]
请问是刚开始运行的时候出现的该报错，还是运行了一段时间以后出现的该报错呢？有没有在这之前的日志呢？

**Comment by lxy4856971** [comment]
> 请问是刚开始运行的时候出现了该报错，还是运行了一段时间以后出现的该报错呢？有没有在这之前的日志呢？
response.StatusCode is: 405, body is: <!doctype html>
<html lang=en>
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p> 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x65d4e5]   通过链接登录微信成功后，只要我发消息问，就退出

**Comment by lxy4856971** [comment]
> > 请问是刚刚开始运行的时候出现了该报错，还是运行了一段时间以后出现的该报错呢？有没有在这之前的日志呢？ response.StatusCode是：405，正文是：<!doctype html 
> > >
> 
> <title>405 方法不允许</title>
> # 方法不允许
> 所请求的 URL 不允许该方法。
> 
> panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x65d4e5] 通过链接登录微信成功后，只要我发信息问题，就退出

这是我pandora运行命令 docker run -e PANDORA_CLOUD=cloud -e PANDORA_SERVER=0.0.0.0:8018 -p 8018:8018 -d pandora

**Comment by xtymbbt** [comment]
我了解了。抱歉没有在README.md中进行体现。目前支持的pandora版本是1.0.10版本，高版本pandora可能暂不兼容。我会在文档中更新说明。

**Comment by lxy4856971** [comment]
> 我了解了。抱歉没有在README.md中进行体现。目前支持的pandora版本是1.0.10版本，高版本pandora可能暂不兼容。我会在文档中更新说明。

2023/06/15 20:55:47 登录成功
ERRO[CST 2023 Jun 15 Thu PM 20:55:53.172352214] response.StatusCode is: 405, body is: <!doctype html>
<html lang=en>
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p> 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x65d4e5]

goroutine 24 [running]:
pandora-wechat/pandoraGpt.Completions({0xc00022e6e0, 0xe}, {0xc0001e96f0, 0xc}, {0xc000103e70?, 0xc0000f5000?})
        /Users/bridge-wang/Coding/chatgpt/pandora-wechat/pandoraGpt/pandora.go:49 +0x1e5
pandora-wechat/handlers.(*UserMessageHandler).ReplyText(0x6bfaa0?, 0xc00007af00)
        /Users/bridge-wang/Coding/chatgpt/pandora-wechat/handlers/user_msg_handler.go:41 +0x1ba
pandora-wechat/handlers.(*UserMessageHandler).handle(0x6ce780?, 0xc000065080?)
        /Users/bridge-wang/Coding/chatgpt/pandora-wechat/handlers/user_msg_handler.go:22 +0x2a
pandora-wechat/handlers.Handler(0xc00007af00)
        /Users/bridge-wang/Coding/chatgpt/pandora-wechat/handlers/handler.go:41 +0xb8
github.com/eatmoreapple/openwechat.(*Bot).syncCheck(0xc0000b6000)
        /Users/bridge-wang/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.2/bot.go:257 +0x21a
github.com/eatmoreapple/openwechat.(*Bot).WebInit.func1()
        /Users/bridge-wang/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.2/bot.go:178 +0x68
created by github.com/eatmoreapple/openwechat.(*Bot).WebInit
        /Users/bridge-wang/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.2/bot.go:173 +0x28b
root@iZ2zebrbk7rtw7afrsilz5Z:~# docker ps
CONTAINER ID   IMAGE                      COMMAND            CREATED         STATUS         PORTS                                       NAMES
fe9980a6fcce   pengzhile/pandora:1.0.10   "bin/startup.sh"   3 minutes ago   Up 3 minutes   0.0.0.0:8018->8018/tcp, :::8018->8018/tcp   strange_proskuriakova
root@iZ2zebrbk7rtw7afrsilz5Z:~#

**Comment by lxy4856971** [comment]
我更换了1.0.10版本 还是这个问题

**Comment by xtymbbt** [comment]
Pandora使用普通模式（不采用cloud模式）再试一下呢？可能是因为pandora cloud模式和普通模式的接口不同导致的。

**Comment by lxy4856971** [comment]
> Pandora使用普通模式（不采用cloud模式）再试一下呢？可能是因为pandora cloud模式和普通模式的接口不同导致的。
试了不行，不弄了，我换了个

**Comment by stephaneThannio** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
erichua23, @Shuiyu007, @Quietly-20201113, @BingkangShi, @zhaodc, @liuping1997, @sousawen, @Polaris-d, @wdlm90, @Han0nly, @seasonstar, @andy14022025, @jasperyang, @yangmengling, @zhouhy0903, @mmyyrroonn, @hlr88828, @DevinChen1, @Joseph-Kuo, @Ngphhoami, @wu19960918, @westinedu, @pizizz, @ChowRex, @LiuDongDaniel, @Jason-lee-lxx, @SteadyHua, @SvenDai, @dragonriverhack, @quefk, @Dandi007, @keychenn, @xingyu316, @caly5144, @Pirate-Xing, @zhaorenjie, @iCpks2, @wongzigii, @flycloud123, @jowngen, @popeyer1, @peterhan, @lis168, @whispor, @linmou, @hxgqh, @haxu5552, @rjzou, @Meta0x00, @eaglelive
